server:
  port: 9000

messaging:
  - weather: 0
  - motion: 1
  - watering: 3


management.endpoints.enabled-by-default: true

management.endpoints.web.exposure.include: "*"

management.security.enabled: false

commander.hostname: "localhost:9999"
